apiVersion: batch/v1
kind: CronJob
metadata:
  name: temporal-demo-worker
spec:
  schedule: "0 */3 * * *" 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: temporal-demo-worker-container
            image: ghcr.io/joao00paixao/temporal-demo:main
            resources:
              limits:
                memory: "128Mi"
                cpu: "200m"
          restartPolicy: Never
