FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o output ./workers/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/output ./
CMD ["/app/output"]
